#docker-compose file - allow multiple images but all at the sametime
version: '3'

services:
  nestapp:
    container_name: nestapp
    image: nestapp:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/nest-mongo-docker-db
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27018:27017"