#docker-compose file - allow multiple images but all at the sametime
version: '3'

services:
  nestapp:
    container_name: nestapp
    image: nestapp:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://mongo:27017/nest-mongo-docker-db
    volumes:
      - ".:/usr/src/app"
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    develop:
      watch:
      - path: ./package.json
        action: rebuild
      - path: ./package-lock.json
        action: rebuild
      - path: .
        target: /usr/src/app
        action: sync

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - D:\Ahyan\Bry_D_drive\Programming\Courses\mongo_db_volume:/data/db
    ports:
      - "27018:27017"